#!/usr/bin/env python

# ----------------------------------------------------------------------------
# Copyright (c) 2013--, IAB development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file COPYING.txt, distributed with this software.
# ----------------------------------------------------------------------------

import click
import random
import string
from biab.util import make_tree, biab_notebook

_input = click.option('-i', '--input',  required=True,
                      type=click.Path(exists=True, file_okay=False))

_output = click.option('-o', '--output', required=True,
                       type=click.Path(writable=True))


cli = click.Group()

@cli.command()
def idgen():
    click.echo('<link src="%s"/>' %
               ''.join(random.choice(string.ascii_letters +
                                     string.digits) for _ in range(6)))

@cli.command()
@_input
def aliases(input):
    tree = make_tree(input)
    for node in tree:
        click.echo("%s\t%s\t%s" % (node.id, node.path, node.title))


@cli.command()
@_input
@_output
@click.option('-z', '--zip', 'should_zip', is_flag=True)
def notebook(input, output, should_zip):
    if should_zip:
        raise NotImplementedError()
    biab_notebook(input, output, 'notebook')


@cli.command()
@_input
@_output
def html(input, output):
    biab_notebook(input, output, 'html')


if __name__ == '__main__':
    cli()
