#!/usr/bin/env python

# ----------------------------------------------------------------------------
# Copyright (c) 2013--, IAB development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file COPYING.txt, distributed with this software.
# ----------------------------------------------------------------------------

import click
import random
import string
import tempfile
import shutil
from biab.util import make_tree, biab_notebook

_input = click.option('-i', '--input',  required=True,
                      type=click.Path(exists=True, file_okay=False))

_output = click.option('-o', '--output', required=True,
                       type=click.Path(writable=True))

_css = click.option('-c', '--css', default=None,
                    type=click.Path(exists=True, dir_okay=False))


cli = click.Group()

@cli.command()
def idgen():
    click.echo('<link src="%s"/>' %
               ''.join(random.choice(string.ascii_letters +
                                     string.digits) for _ in range(6)))

@cli.command()
@_input
def aliases(input):
    tree = make_tree(input)
    for node in tree:
        click.echo("%s\t%s\t%s" % (node.id, node.path, node.title))


@cli.command()
@_input
@_output
@click.option('-z', '--zip', 'should_zip', is_flag=True)
def notebook(input, output, should_zip):
    if should_zip:
        raise NotImplementedError()
    biab_notebook(input, output, 'notebook')


@cli.command()
@_input
@_output
@_css
def html(input, output, css):
    biab_notebook(input, output, 'html', css=css)


@cli.command()
@_input
@_output
@_css
def s3build(input, output, css):
    biab_notebook(input, output, 's3', css=css)

@cli.command()
@_input
@click.option('-v', '--version', required=True)
def s3upload(input, version):
    from biab.s3 import upload_s3_book
    upload_s3_book(version, input)

if __name__ == '__main__':
    cli()
